# CONFIGURACIÓN DIRECTA DE ORACLE CLOUD (Sin depender de alias tnsnames)
spring.datasource.url=jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=gc3b947da08b29a_mbd_medium.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=ADMIN
spring.datasource.password=DUOCmbd#2026

# Propiedades de ubicación para los certificados de seguridad mutua (mTLS)
oracle.net.tns_admin=/app/src/main/resources/Wallet_MBD
oracle.net.wallet_location=/app/src/main/resources/Wallet_MBD


# Configuración de JPA / Hibernate
# Reemplaza tu propiedad de dialecto por esta:
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CONFIGURACIÓN DE CREDENCIALES Y SERVICIOS AWS
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:REMPLAZAR_EN_EL_SERVIDOR}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:REMPLAZAR_EN_EL_SERVIDOR}
spring.cloud.aws.credentials.session-token=${AWS_SESSION_TOKEN:REMPLAZAR_EN_EL_SERVIDOR}
spring.cloud.aws.region.static=us-east-1

# Solución al Punto 1 de la retroalimentación (Inyección dinámica del Bucket)
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:bucketduoc-s1}
