# Configuración de Oracle Cloud con Wallet
spring.datasource.url=jdbc:oracle:thin:@mbd_medium?TNS_ADMIN=/app/src/main/resources/Wallet_MBD/
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=ADMIN
spring.datasource.password=DUOCmbd#2026

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CONFIGURACIÓN DE CREDENCIALES Y SERVICIOS AWS
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:REMPLAZAR_EN_EL_SERVIDOR}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:REMPLAZAR_EN_EL_SERVIDOR}
spring.cloud.aws.credentials.session-token=${AWS_SESSION_TOKEN:REMPLAZAR_EN_EL_SERVIDOR}
spring.cloud.aws.region.static=us-east-1

# Solución al Punto 1 de la retroalimentación (Inyección dinámica del Bucket)
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:bucketduoc-s1}
